# Generated by Django 6.0.2 on 2026-07-26 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0013_remove_item_masters_ite_event_i_0de268_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(blank=True, max_length=255, verbose_name='Volunteer Name')),
                ('volunteer_mobile', models.CharField(blank=True, max_length=20, verbose_name='Volunteer Mobile')),
                ('event_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Event Rating')),
                ('portal_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Portal Rating')),
                ('event_feedback', models.TextField(blank=True, verbose_name='Event Feedback')),
                ('portal_feedback', models.TextField(blank=True, verbose_name='Portal Feedback / Issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='masters.event')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
