# Generated by Django 6.0.2 on 2026-06-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_event_primary_contacts_eventmanagercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanagercontact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='masters.event'),
        ),
    ]
