# Generated by Django 6.0.2 on 2026-06-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_item_standard_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['standard_serial', 'item_name']},
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='masters_ite_event_i_82abf5_idx',
            old_name='masters_item_event_8b04eb_idx',
        ),
    ]
