# Generated by Django 6.0.2 on 2026-06-25 10:25

import uuid

from django.db import migrations, models


def populate_public_form_tokens(apps, schema_editor):
    Event = apps.get_model("masters", "Event")
    existing = set(Event.objects.exclude(public_form_token__isnull=True).values_list("public_form_token", flat=True))
    for event in Event.objects.filter(public_form_token__isnull=True).order_by("pk"):
        token = uuid.uuid4()
        while token in existing:
            token = uuid.uuid4()
        Event.objects.filter(pk=event.pk).update(public_form_token=token)
        existing.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_form_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_form_tokens, migrations.RunPython.noop),
    ]
