# Generated by Django 6.0.2 on 2026-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_event_public_form_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_requirement_edit_after_confirm',
            field=models.BooleanField(default=True),
        ),
    ]
