# Generated by Django 6.0.2 on 2026-06-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


VARIANT_MAP = {
    17: ["Safed", "Navpad"],
    20: ["3 Liter", "4 Liter"],
    25: ["4 inch", "Plastic Dish"],
    26: ["10 kali", "12 kali"],
    30: ["Red", "Blue", "Green", "Black"],
    53: ["Sadi", "Nani (1 gm)"],
    54: ["Kalo", "Safed"],
    57: ["Green", "Orange", "Blue"],
    59: ["Nani Gol", "Medium"],
    76: ["Simple", "Digital"],
}


def seed_variants(apps, schema_editor):
    Item = apps.get_model("masters", "Item")
    for parent_serial, variants in VARIANT_MAP.items():
        parent = Item.objects.filter(standard_serial=parent_serial, parent_item__isnull=True).first()
        if not parent:
            continue
        for index, variant_name in enumerate(variants, start=1):
            variant_code = f"{parent_serial}{index:02d}"
            if Item.objects.filter(event=parent.event, parent_item=parent, variant_name=variant_name).exists():
                continue
            Item.objects.create(
                event=parent.event,
                parent_item=parent,
                standard_serial=parent_serial * 100 + index,
                item_code=f"{parent.item_code}-{index:02d}",
                item_name=parent.item_name,
                item_name_gu=parent.item_name_gu,
                variant_name=variant_name,
                variant_name_gu="",
                category=parent.category,
                unit=parent.unit,
                default_size=parent.default_size,
                description=parent.description,
                estimated_rate=parent.estimated_rate,
                is_active=parent.is_active,
                is_deleted=False,
            )


def unseed_variants(apps, schema_editor):
    Item = apps.get_model("masters", "Item")
    for parent_serial in VARIANT_MAP:
        parent = Item.objects.filter(standard_serial=parent_serial, parent_item__isnull=True).first()
        if parent:
            Item.objects.filter(event=parent.event, parent_item=parent).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_event_allow_requirement_edit_after_confirm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='masters.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_name_gu',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('event', 'parent_item', 'variant_name'), name='unique_event_item_variant_name'),
        ),
        migrations.RunPython(seed_variants, unseed_variants),
    ]
