# Generated by Django 6.0.2 on 2026-06-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_item_parent_item_item_variant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_code', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RouteSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_code', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('route_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='masters.routearea')),
            ],
            options={
                'ordering': ['route_area__display_order', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='upashray',
            name='sub_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upashrays', to='masters.routesubarea'),
        ),
    ]
