# Generated by Django 6.0.2 on 2026-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_routearea_routesubarea_upashray_sub_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_size_gu',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
