# Generated by Django 6.0.2 on 2026-07-22 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_item_default_size_gu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['event', 'is_active', 'parent_item_id', 'standard_serial'], name='masters_ite_event_i_0de268_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['event', 'is_active', 'item_code'], name='masters_ite_event_i_1ef01f_idx'),
        ),
    ]
