# Generated by Django 6.0.2 on 2026-07-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_item_masters_ite_event_i_0de268_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='masters_ite_event_i_0de268_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='masters_ite_event_i_1ef01f_idx',
        ),
    ]
