# Generated by Django 6.0.2 on 2026-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_remove_item_masters_ite_event_i_0de268_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepting_responses',
            field=models.BooleanField(default=True, help_text='When enabled, anyone can see and submit the Collect Requirement form. When disabled, the form is hidden and a completion message is shown instead.'),
        ),
    ]
