# Generated by Django 6.0.2 on 2026-08-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_event_accepting_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(help_text='ઈવેન્ટનું વર્ષ (e.g. 2024)')),
                ('month', models.CharField(help_text="ગુજરાતીમાં મહિનો અથવા તારીખોની રેન્જ લખો, e.g. 'ફેબ્રુઆરી' અથવા 'જૂન–જુલાઈ'.", max_length=60)),
                ('month_order', models.SmallIntegerField(default=13, editable=False)),
                ('title', models.CharField(help_text='હેડિંગ ગુજરાતીમાં લખો. 200 અક્ષરથી વધુ નહીં.', max_length=200)),
                ('description', models.TextField(help_text='વર્ણન ગુજરાતીમાં લખો. કાર્ડની ઊંચાઈ જાળવવા માટે 600 અક્ષરની મર્યાદામાં રહો (લગભગ 30 શબ્દો).', max_length=600)),
                ('category', models.CharField(choices=[('animal', 'જીવદયા (Animal Welfare)'), ('medical', 'મેડિકલ રાહત (Healthcare)'), ('education', 'શિક્ષણ/પાઠશાળા (Education)'), ('social', 'અનુકંપાદાન (Social Relief)')], default='social', help_text='કાર્ડનું વર્ગીકરણ (ટાઈમલાઈનમાં રંગ અને ફિલ્ટર માટે).', max_length=40)),
            ],
            options={
                'verbose_name': 'Journey card',
                'verbose_name_plural': 'Journey cards',
                'ordering': ['year', 'month_order', 'id'],
            },
        ),
    ]
