# Generated by Django 6.0.2 on 2026-07-31 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaselot_inventorytransaction_purchase_lot_and_more'),
        ('masters', '0013_remove_item_masters_ite_event_i_0de268_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('DONATION', 'Donation'), ('SPONSORSHIP_RECEIPT', 'Sponsorship Receipt'), ('DISTRIBUTION', 'Distribution'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('OPENING_BALANCE', 'Opening Balance')], max_length=40),
        ),
        migrations.CreateModel(
            name='RemainingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('carried_at', models.DateTimeField(blank=True, null=True)),
                ('carried_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('carried_to_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.event')),
                ('carried_to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.item')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='masters.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_stock_records', to='masters.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event__start_date', 'item__standard_serial', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('event', 'item'), name='unique_remaining_stock_event_item')],
            },
        ),
    ]
