# Generated by Django 6.0.2 on 2026-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirementheader_finalization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='chaturmas_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='chaturmas_place_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='current_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='pujya_shri_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='stay_type',
            field=models.CharField(blank=True, choices=[('SANGH_UPASHRAY', 'Sangh Upashray'), ('STHIRVAS', 'Sthirvas')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='thana_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='volunteer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='your_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
