# Generated by Django 6.0.2 on 2026-06-25 10:25

import uuid

from django.db import migrations, models


def populate_public_view_tokens(apps, schema_editor):
    RequirementHeader = apps.get_model("requirements", "RequirementHeader")
    existing = set(
        RequirementHeader.objects.exclude(public_view_token__isnull=True).values_list("public_view_token", flat=True)
    )
    for header in RequirementHeader.objects.filter(public_view_token__isnull=True).order_by("pk"):
        token = uuid.uuid4()
        while token in existing:
            token = uuid.uuid4()
        RequirementHeader.objects.filter(pk=header.pk).update(public_view_token=token)
        existing.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_requirementheader_caretaker_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='public_view_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_view_tokens, migrations.RunPython.noop),
    ]
