# Generated by Django 6.0.2 on 2026-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0009_requirementheader_public_view_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='packing_stock_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirementheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('SUBMITTED', 'Pending'), ('IN_PROGRESS', 'Packing done'), ('CLOSED', 'On route'), ('CANCELLED', 'Rejected by M.S.'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_DONE', 'Return Done'), ('RECEIVED_BY_MS', 'Recieved by M.S.')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='specialrequirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('SUBMITTED', 'Pending'), ('IN_PROGRESS', 'Packing done'), ('CLOSED', 'On route'), ('CANCELLED', 'Rejected by M.S.'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_DONE', 'Return Done'), ('RECEIVED_BY_MS', 'Recieved by M.S.')], default='DRAFT', max_length=30),
        ),
    ]
