# Generated by Django 6.0.2 on 2026-06-28 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_item_default_size_gu'),
        ('requirements', '0010_requirementheader_packing_stock_applied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementheader',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='requirementheader',
            constraint=models.UniqueConstraint(fields=('event', 'order_number'), name='unique_event_order_number'),
        ),
    ]
