# Generated by Django 6.0.2 on 2026-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0011_add_event_order_number_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='route_area',
            field=models.CharField(blank=True, choices=[('A1', 'Area-1 City-ReliefRoad'), ('A2', 'Area-2 Shahpur-Usmanpura'), ('A3', 'Area-3 Naranpura-Thaltej'), ('A4', 'Area-4 Vadaj Subhashbridge'), ('A5', 'Area-5 KrishnaNagar-Naroda'), ('A6', 'Area-6 Jivrajpark-Satellite'), ('A7', 'Area-7 Vasna-New Vasna'), ('A8', 'Area-8 Paldi-ChandraNagar'), ('A9', 'Area-9 Shahibag'), ('A10', 'Area-10 Sabarmati-Chandkheda'), ('A11', 'Area-11 Other Areas')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requirementheader',
            name='volunteer_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
