# Generated by Django 6.0.2 on 2026-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0012_requirementheader_route_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='route_sub_area',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
