# Generated by Django 6.0.2 on 2026-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0014_alter_requirementheader_route_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementheader',
            name='form_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Form No.'),
        ),
        migrations.AlterField(
            model_name='requirementheader',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Order ID'),
        ),
    ]
