# Generated by Django 6.0.2 on 2026-06-29 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_item_default_size_gu'),
        ('requirements', '0015_requirementheader_form_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('NOT_CONFIRMED', 'Not Confirmed'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Pending'), ('PACKED', 'Packed'), ('IN_PROGRESS', 'Packing done'), ('DELIVERED', 'Delivered'), ('CLOSED', 'On route'), ('CANCELLED', 'Rejected by M.S.'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_DONE', 'Return Done'), ('RECEIVED_BY_MS', 'Recieved by M.S.')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='specialrequirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Open'), ('NOT_CONFIRMED', 'Not Confirmed'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Pending'), ('PACKED', 'Packed'), ('IN_PROGRESS', 'Packing done'), ('DELIVERED', 'Delivered'), ('CLOSED', 'On route'), ('CANCELLED', 'Rejected by M.S.'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_DONE', 'Return Done'), ('RECEIVED_BY_MS', 'Recieved by M.S.')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='masters.event')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='requirements.requirementheader')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
