# Generated by Django 6.0.2 on 2026-06-30 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_item_default_size_gu'),
        ('requirements', '0016_alter_requirementheader_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_form_number', models.BooleanField(default=True, verbose_name='Form No.')),
                ('show_order_id', models.BooleanField(default=True, verbose_name='Order ID')),
                ('show_route', models.BooleanField(default=True, verbose_name='Route')),
                ('show_sub_route', models.BooleanField(default=True, verbose_name='Sub Route')),
                ('show_pujya_shri', models.BooleanField(default=True, verbose_name='Pujya Shri')),
                ('show_thana', models.BooleanField(default=True, verbose_name='Thana')),
                ('show_area', models.BooleanField(default=True, verbose_name='Area')),
                ('show_form_date', models.BooleanField(default=True, verbose_name='Form Date')),
                ('show_current_address', models.BooleanField(default=True, verbose_name='Current Address')),
                ('show_chaturmas_address', models.BooleanField(default=True, verbose_name='Chaturmas Address')),
                ('show_chaturmas_entry_date', models.BooleanField(default=True, verbose_name='Chaturmas Entry Date')),
                ('show_volunteer_name', models.BooleanField(default=True, verbose_name='Volunteer Name')),
                ('show_volunteer_mobile', models.BooleanField(default=True, verbose_name='Volunteer Mobile')),
                ('show_stay_type', models.BooleanField(default=True, verbose_name='Stay Type')),
                ('show_caretaker_name', models.BooleanField(default=True, verbose_name='Care Taker Name')),
                ('show_caretaker_mobile', models.BooleanField(default=True, verbose_name='Care Taker Mobile')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_control', to='masters.event')),
            ],
            options={
                'verbose_name': 'View Control',
                'verbose_name_plural': 'View Controls',
            },
        ),
    ]
