# Generated by Django 6.0.2 on 2026-06-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0017_viewcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='resolution',
            field=models.CharField(choices=[('UNSOLVED', 'Unsolved'), ('SOLVED', 'Solved'), ('REJECTED', 'Rejected')], default='UNSOLVED', max_length=20),
        ),
    ]
