# Generated by Django 6.0.2 on 2026-06-18 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('home_delivery', models.BooleanField(default=False)),
                ('pickup_available', models.BooleanField(default=False)),
                ('return_unused', models.BooleanField(default=False)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('gst_included', models.BooleanField(default=False)),
                ('quote_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='masters.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_quotes', to='masters.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='masters.vendor')),
            ],
            options={
                'ordering': ['rate', 'quote_date'],
                'indexes': [models.Index(fields=['event', 'item', 'rate'], name='vendors_ven_event_i_f927b8_idx')],
            },
        ),
    ]
