from django.urls import path

from apps.requirements.views import (
    EditRequestCreateView,
    EditRequestListView,
    EditRequestResolveView,
    RequirementHeaderCreateView,
    RequirementHeaderDeleteView,
    RequirementCollectionDetailView,
    RequirementHeaderExportView,
    RequirementHeaderListView,
    RequirementHeaderUpdateView,
    RequirementCollectByEventView,
    RequirementCollectionPrintView,
    RequirementRejectView,
    RequirementStatusTransitionView,
    RequirementUnlockView,
    RequirementLockView,
    RequirementLineCreateView,
    RequirementLineDeleteView,
    RequirementLineListView,
    RequirementLineUpdateView,
    RevertToPackedView,
    SpecialRequirementCreateView,
    SpecialRequirementDeleteView,
    SpecialRequirementListView,
    SpecialRequirementUpdateView,
    StockBasedPackingView,
    ViewControlView,
)

app_name = "requirements"

urlpatterns = [
    path("", RequirementHeaderListView.as_view(), name="header-list"),
    path("export/", RequirementHeaderExportView.as_view(), name="header-export"),
    path("collect/", RequirementCollectByEventView.as_view(), name="collect"),
    path("collect/<int:pk>/", RequirementCollectByEventView.as_view(), name="collect-edit"),
    path("collect/<int:pk>/view/", RequirementCollectionDetailView.as_view(), name="header-detail"),
    path("collect/<int:pk>/print/", RequirementCollectionPrintView.as_view(), name="collect-print"),
    path("public/<uuid:event_token>/collect/", RequirementCollectByEventView.as_view(), name="public-collect"),
    path("public/<uuid:token>/", RequirementCollectionDetailView.as_view(), name="public-detail"),
    path("public/<uuid:token>/print/", RequirementCollectionPrintView.as_view(), name="public-print"),
    path("add/", RequirementHeaderCreateView.as_view(), name="header-create"),
    path("<int:pk>/edit/", RequirementHeaderUpdateView.as_view(), name="header-update"),
    path("<int:pk>/delete/", RequirementHeaderDeleteView.as_view(), name="header-delete"),
    path("lines/", RequirementLineListView.as_view(), name="line-list"),
    path("lines/add/", RequirementLineCreateView.as_view(), name="line-create"),
    path("lines/<int:pk>/edit/", RequirementLineUpdateView.as_view(), name="line-update"),
    path("lines/<int:pk>/delete/", RequirementLineDeleteView.as_view(), name="line-delete"),
    path("special/", SpecialRequirementListView.as_view(), name="special-list"),
    path("special/add/", SpecialRequirementCreateView.as_view(), name="special-create"),
    path("special/<int:pk>/edit/", SpecialRequirementUpdateView.as_view(), name="special-update"),
    path("special/<int:pk>/delete/", SpecialRequirementDeleteView.as_view(), name="special-delete"),
    path("collect/<int:pk>/transition/", RequirementStatusTransitionView.as_view(), name="status-transition"),
    path("collect/<int:pk>/reject/", RequirementRejectView.as_view(), name="reject"),
    path("collect/<int:pk>/revert-to-packed/", RevertToPackedView.as_view(), name="revert-to-packed"),
    path("collect/<int:pk>/unlock/", RequirementUnlockView.as_view(), name="header-unlock"),
    path("collect/<int:pk>/lock/", RequirementLockView.as_view(), name="header-lock"),
    path("collect/<int:pk>/edit-request/", EditRequestCreateView.as_view(), name="edit-request"),
    path("public/<uuid:token>/edit-request/", EditRequestCreateView.as_view(), name="public-edit-request"),
    path("edit-requests/", EditRequestListView.as_view(), name="edit-request-list"),
    path("edit-requests/<int:pk>/resolve/", EditRequestResolveView.as_view(), name="edit-request-resolve"),
    path("view-control/", ViewControlView.as_view(), name="view-control"),
    path("pack-by-order/", StockBasedPackingView.as_view(), name="pack-by-order"),
]

